"""BLUME SALAMANCA telegram no. 1, Zurich to London, 8 Jan 1937 (Schmeh's Facebook post, photo from Regula Bochsler).
123 five-letter groups; with BLUME SALAMANCA = 125 words, matching the '125' in the word-count box."""
T1 = """SSVCC NTEMS AEPZE UQNOC URNRM RSIUO BSBHD ONSBB
OAOEP MINGA CTPOO PANPO APIEI EATTH IUDEE ENGIO
MAREO LGMAL EEMNE IAPSI HLTOS NTONI AIACA UOSSU
YSRIT TIERD POAFE ENPEA OSAOA NNOGR UBOOI ANDDE
OEUOR AEATN TPICE ARARE NMOAS SOIRS STBJC IOEIC
DIOND IINPE NONCA VPTEE VDHOS PANRO OASTE ACCEI
APITC GRONO NSSOS IPOON EZEAP MOEPA IIORT RSPAT
CBDDT AOOOK MJEET EEESN ANLPS DCERC EMIOZ NDTOD
DTERA CBEFR SZRTS EDMCC ASACT AITDO RPONO BADMN
RTXMN OUAER URCHR AEMBN RINRU NLONO REOLP EEIRC
MOOOE EHEOI LTSYL QORCE ANANX AOTSP OARMT SELAG
XMSPN TTETI RNIMR GRPOU ORMLI SEENE HDETP DOIMA
NUHIG TNCEN OTNOT INERM AOUAM LIAIN CPCSE UNCEM
BDLSS SAAIE OAEEA FSIEP MATOO NSEGC OSEPI RAEED
RBEEP DRODL NDNOI EONRP PNPIL APCOA CPICE AXLNK
IPLAN FTUIX REFLX"""
GROUPS = T1.split()
CT = ''.join(GROUPS).lower()
