CRYPTOGRAMS = [
 ("A","SKCDKJCDJCYQSZKTZJPXPWIRN"),
 ("B","MQOLCSJTLGAJOKBSSBOMUPCE"),
 ("C","RHZVIYQIYSXVNQXQWIOVWPJO"),
 ("D","FEWGDRHDDEEUMFFTEEMJXZR"),
 ("E","XLYPISNANIRUSFTFWMIY"),
 ("F","HFXPCQYZVATXAWIZPVE"),
 ("G","YQHUDTABGALLOWLS"),
 ("H","UGMNCBXCFLDBEY"),
 ("I","ABRYCTUGVZXUPB"),
 ("J","JKGFIJPMCWSAEK"),
 ("K","KOWVRSRKWTMLDH"),
 ("L","HLMTAHGBGFNIV"),
 ("M","MVERZRLQDBHQ"),
 ("N","VIOHIKNNGUAB"),
 ("O","GKJFHYXODIE"),
 ("P","ZUQUPNZN"),
]
ALL = ''.join(c for _,c in CRYPTOGRAMS)
